### ISSUE TITLE
Adding Jupytext as a requirement

### ISSUE THREAD

**Issue by emdupre** [alexprz/meta_analysis_notebook#14]
It'd be great if this repository could use [Jupytext](https://github.com/mwouts/jupytext), such that a Python script rather than a Jupyter Notebook was tracked on GitHub. This would make it much easier to maintain human-readable version control !

Happy to help point in the right direction, here.

**Comment by aperezlebel** [comment]
Thank you for your idea! It should be fixed in 6f3b126401920a4ddad42cffae304e03cd8332e9.
